
GET https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces
###

POST https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces
###


POST https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Paris"
}
###

GET https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=6464
###

PUT https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=6464
Content-Type: application/json

{
    "location": "Stockholm"
}
###

DELETE https://kkfzb7iszh.execute-api.eu-central-1.amazonaws.com/prod/spaces?id=6464
###